name: Mean Time to First Commit

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  mean-time-to-first-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm install --omit=dev
      - name: Collect MTTFC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm start \
          | grep Mean \
          | sed "s/$/: $(date)/" \
          | sed 's/: /,/g' >> mttfc-report.csv
      - name: Update Report
        run: |
          git config --global user.name "MTTFC Job"
          git config --global user.email "mttfc-job@va.gov"
          git add mttfc-report.csv
          git commit -m "Update MTTFC Report"
          git push
