name: Mean Time to First Commit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mean-time-to-first-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --omit=dev
      - name: Collect MTTFC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # npm start > results.txt
          # cat results.txt | grep Mean >> mttfc-report.csv
          echo -n 'Mean Time to First Commit based on Roster: 104.24 days' | grep Mean >> mttfc-report.csv
      - name: Update Report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global commit.gpgsign true
          git add mttfc-report.csv
          git commit -m "Update MTTFC Report"
          git push
