name: Mean Time to First Commit

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  mean-time-to-first-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --omit=dev
      - name: Collect MTTFC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm start
